server:
  port: 8888
spring:
  application:
    name: FastDFS-Demo
  http:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:    #缩略图生成参数
    width: 150
    height: 150
  trackerList:   #TrackerList参数,支持多个
    - 192.168.158.141:22122
  pool:
    max-total: 153  #从池中借出的对象的最大数目
    max-wait-millis: 102  #获取连接时的最大等待毫秒数100
# 自定义配置
appConfig:
  res-host: 192.168.158.141
  fdfs-storage-port: 8888
# 分布式文件系统FDFS配置
